In [100]:
import numpy as np
import matplotlib.pyplot as plt

In [101]:
def LUmine(A) :
    n = A.shape[0]
    L = np.matrix( np.identity(n) )
    U = A
    for j in range(0, n-1):
        for i in range (j+1, n) :
            mult = A[i,j] / A[j,j]
            A[i, j+1:n] = A[i,j+1:n] - mult * A[j,j+1:n]
            U[i, j+1:n] = A[i, j+1:n]           
            L[i,j] = mult
            U[i,j] = 0
    return L, U

def QRmine(A):
    n = A.shape[0]
    Q = np.zeros((n, n))
    for j in range(n):
        q = A[:, j]
        for i in range(j):
            length_of_leg = np.sum(A[:, j].T * Q[:, i])
            q = q - length_of_leg * Q[:, j]
        Q[:, j] = q / np.linalg.norm(q)
    R = Q.T @ A
    return Q, R


In [102]:
def create_hilbert_matrix(n):
    H = np.zeros((n, n))
    for i in range(1, n+1):
        for j in range(1, n+1):
            H[i-1, j-1] = 1 / (i + j - 1)
    return H

n = 4 # ορίζουμε το μέγεθος n του πίνακα Hilbert
H = create_hilbert_matrix(n)
print(H)


[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]


In [103]:
def solve_system(A, b):
    L, U = LUmine(A)
    y = np.linalg.solve(L, b)
    x = np.linalg.solve(U, y)
    return x
b = np.ones((n, 1))

x = solve_system(H, b)

In [104]:
Q_transpose = Q.transpose()
R_inverse = np.linalg.inv(R)
b_new = b + 10**(-15)
x_new = solve_system(H,b_new)
diff = np.max(np.abs(x - x_new))
print(diff)

3839.999999999843


Παρατηρούμε πως η μέγιστη απόλυτη διαφορά είναι πολύ μεγάλο μέγεθος

In [105]:
#Λείπει το ερώτημα δ

In [106]:
H_inverse = np.linalg.inv(H)
calc = np.matmul(H,H_inverse)
print(calc)
newmatrix = np.identity(n) - calc
vec_norm = np.linalg.norm(newmatrix)


[[ 1.00000000e+00  0.00000000e+00  1.40628250e-15  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -2.47949809e-15  1.40332190e-14]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  6.95739762e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
